config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admins do
    get 'events/new'
    root 'homes#index'
    get 'join_error', to: 'events/members#join_error', as: 'join_error'
    resources :users
    resources :events do
      resources :groups, module: :events
      resources :members, only: [:show], module: :events do
        get 'join', on: :collection
        post 'resend', on: :member
      end
    end
  end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :department
  has_many :members
  has_many :groups, through: :members

  enum position: { intern: 0, staff: 10, manager: 20, executive: 30 }
  enum state: { enable: 0, disable: 1 }

  scope :order_desc, -> { order( "users.id DESC" ) }
  scope :enabled, -> { where(state: :enable) }
  scope :ordered_position, -> {
    joins(:department).order('departments.position ASC')
  }

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w\-._]+@[\w\-._]+\.[A-Za-z]+(?:,[\w\-._]+@[\w\-._]+\.[A-Za-z]+)*\z/
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < Admins::BaseController
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.ordered_position.page(params[:page])
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find params[:id]
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admins_user_path(@user), notice: 'ユーザーが登録されました。'
    else
      flash[:alert] = "登録に失敗しました。"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admins_user_path(@user), notice: 'ユーザーが更新されました。'
    else
      flash[:alert] = "更新に失敗しました。"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    redirect_to admins_users_path, notice: 'ユーザーが削除されました。'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :position, :department_id, :state)
  end
end

app/views/admins/users/edit.html.slim
.container
  .header-container
    h2.heading-ttl ユーザー編集画面

  .form-container
    = form_with(model: @user, url: admins_user_path(@user), method: :patch, local: true, class: "edit-form") do |f|
      .form-inner

        .form-item
          = f.label :state, 'ステータス'
          = f.select :state, User.states_i18n.invert.to_a, { prompt: '選択してください。' }, class: 'form-control'

        .form-item
          = f.label :name, '名前 (例：開発太郎)', class: 'required-label'
          = f.text_field :name, class: 'form-control', placeholder: '名前を入力してください'

        .form-item
          = f.label :email, 'メールアドレス', class: 'required-label'
          = f.email_field :email, class: 'form-control', placeholder: 'メールアドレスを入力してください'

        .form-item
          = f.label :position, '役職'
          = f.select :position, User.positions_i18n.invert.to_a, { prompt: '選択してください。' }, class: 'form-control'

        .form-item
          = f.label :department_id, '部署'
          = f.select :department_id, Department.all.map { |d| [d.name, d.id] }, { prompt: '選択してください。' }, class: 'form-control'

        = f.submit '更新', class: 'btn-submit'

app/views/admins/users/index.html.slim
.container
  .header-container
    h2.heading-ttl ユーザー
    .header-btn
      = link_to new_admins_user_path, class: 'user-new-btn' do
        span.icon-text ＋
        = image_tag 'person_icon.png', alt: 'Role Icon', class: 'btn-icon'

  table.table.pc-table
    thead
      tr
        th ステータス
        th 部署
        th 氏名
        th メールアドレス
        th 役職
        th 編集
    tbody
      - @users.each do |user|
        tr
          td
            - if user.state == 'enable'
              span.badge.badge__enable 有効
            - else
              span.badge.badge__disable 無効
          td = user.department.name
          td
            = link_to user.name, admins_user_path(user), class: 'table__name'
          td = user.email
          td = position_badge(user)
          td
            = link_to edit_admins_user_path(user) do
              = image_tag 'pencil.png', alt: 'Edit', class: 'icon'

  // SP画面用のリスト表示
  ul.list-view
    - @users.each do |user|
      li
        = link_to admins_user_path(user), class: 'list-view__link' do
          .list-view__icon
            = image_tag 'account_circle.png', alt: 'user', class: 'icon-user'
          .list-view__user-name = user.name
          .list-view__arrow
            = image_tag 'arrow_icon.png', alt: 'arrow', class: 'icon-arrow'


  .pc-pagenation
    = paginate @users

app/views/admins/users/new.html.slim
.container
  .header-container
    h2.heading-ttl ユーザー作成画面

  .form-container
    = form_with(model: @user, url: admins_users_path, method: :post, local: true, class: "edit-form") do |f|
      .form-inner

        .form-item
          = f.label :state, 'ステータス'
          = f.select :state, User.states_i18n.invert.to_a, { prompt: '選択してください。' }, class: 'form-control'

        .form-item
          = f.label :name, '名前 (例：開発太郎)', class: 'required-label'
          = f.text_field :name, class: 'form-control', placeholder: '名前を入力してください'

        .form-item
          = f.label :email, 'メールアドレス', class: 'required-label'
          = f.email_field :email, class: 'form-control', placeholder: 'メールアドレスを入力してください'

        .form-item
          = f.label :position, '役職'
          = f.select :position, User.positions_i18n.invert.to_a, { prompt: '選択してください。' }, class: 'form-control'

        .form-item
          = f.label :department_id, '部署'
          = f.select :department_id, Department.all.map { |d| [d.name, d.id] }, { prompt: '選択してください。' }, class: 'form-control'

        = f.submit '作成', class: 'btn-submit'

app/views/admins/users/show.html.slim
.header-container
  h2.heading-ttl ユーザー詳細画面

.user-show

  .user-show__container
    .user-show__cover-image
      = image_tag 'background_image.jpg', alt: 'Cover Image', class: 'cover-image'

    .user-show__overlay
      .user-show__icon-container
        = image_tag 'account_circle.png', alt: 'User Icon', class: 'user-show__icon'
        .user-show__name-box
          h2.user-show__name = @user.name
          = link_to edit_admins_user_path(@user) do
            = image_tag 'pencil.png', alt: 'Edit', class: 'user-show__icon-pencil'

    .user-show__details
      ul.user-show__info
        li.user-show__info-item
          = image_tag 'role_icon.png', alt: '役職', class: 'user-show__icon-small'
          span = @user.position_i18n

        li.user-show__info-item
          = image_tag 'email_icon.png', alt: 'メール', class: 'user-show__icon-small'
          span = @user.email

        li.user-show__info-item
          = image_tag 'department_icon.png', alt: '部署', class: 'user-show__icon-small'
          span = @user.department.name
    
    .user-show__btn-container
      = link_to '削除', admins_user_path(@user), data: { turbo_method: :delete }, class: 'user-show__delete-btn', onclick: "return confirm('本当にこのユーザーを削除しますか？')"