config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admins do
    get 'events/new'
    root 'homes#index'
    get 'join_error', to: 'events/members#join_error', as: 'join_error'
    resources :users
    resources :events do
      resources :groups, module: :events
      resources :members, only: [:show], module: :events do
        get 'join', on: :collection
        post 'resend', on: :member
      end
    end
  end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }
end

app/views/admins/shared/_header.html.slim
.header
  .header__container
    .header__page-title
      = link_to admins_root_path, class: 'header__ttl' do
        h1= "MixTeam"
    - if admin_signed_in?
      = check_box_tag 'menu-toggle', '', false, id: 'menu-toggle', class: 'header__menu-toggle'
      label.header__hamburger for="menu-toggle"
        .bar
        .bar
        .bar

      nav.header__menu-container
        .header__menu-item
          = link_to 'ホーム', admins_root_path, class: 'header__menu-link'
        .header__menu-item
          = link_to 'ユーザー', admins_users_path, class: 'header__menu-link'
        .header__menu-item
          = link_to 'マイページ', '#', class: 'header__menu-link'
        .header__menu-item
          = link_to 'ログアウト', destroy_admin_session_path, method: :delete, data: { turbo_method: :delete }, class: 'header__menu-link'

          admins_users