config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admins do
    get 'events/new'
    root 'homes#index'
    get 'join_error', to: 'events/members#join_error', as: 'join_error'
    resources :users
    resources :events do
      resources :groups, module: :events
      resources :members, only: [:show], module: :events do
        get 'join', on: :collection
        post 'resend', on: :member
      end
    end
  end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :groups, dependent: :destroy
  has_many :members, dependent: :destroy
  has_many :users, through: :members

  validates :title, presence: true, length: { maximum: 15 }
  validates :event_date, presence: true
  validates :max_group_size, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 2 }
  validates :min_group_size, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 2 }
  validates :memo, length: { maximum: 150 }
  validate :min_group_size_should_be_less_than_max_group_size
  validate :max_and_min_group_size_difference

  enum state: { disable: 0, entry: 1, closed: 2 }

  scope :active, -> { where.not(state: :disable) }
  scope :ordered_desc, -> { order(created_at: :desc) }

  private

  def min_group_size_should_be_less_than_max_group_size
    unless min_group_size.present? && max_group_size.present?
      errors.add(:base, "最小グループサイズおよび最大グループサイズは必須です")
      return
    end
  
    if min_group_size > max_group_size
      errors.add(:min_group_size, "は最大グループサイズ以下である必要があります")
    end
  
    enabled_user_count = User.enabled.count
    if max_group_size > enabled_user_count
      errors.add(:max_group_size, "は現在の有効なユーザー数以下である必要があります（#{enabled_user_count}人以下）")
    end
  end

  def max_and_min_group_size_difference
    if max_group_size.present? && min_group_size.present? && (max_group_size - min_group_size > 1)
      errors.add(:base, "最小グループサイズと最大グループサイズの差は1以内にしてください")
    end
  end
    
end

app/controllers/admins/events/groups_controller.rb
class Admins::Events::GroupsController < Admins::BaseController
  require 'net/http'
  require 'uri'
  require 'json' 

  before_action :set_event_and_member

  def create
    min_members_required = 10
    max_attempts = 10000
    attempt = 0

    if @event.members.count < min_members_required
      redirect_to admins_event_path(@event), alert: "グループ分けには#{min_members_required}人以上の参加が必要です。" and return
    end

    group_sizes = build_group_sizes(@event)

    loop do
      attempt += 1
      
      mix_members = evenly_managers(@members, group_sizes)
      grouped_members = group_members(mix_members, group_sizes)
      
      if member_overlap?(grouped_members) || attempt >= max_attempts
        create_groups(@event, grouped_members)
        redirect_to admins_event_path(@event), notice: 'グループが正常に作成されました。'
        break
      end
    end
  
    @event.update(state: :closed)
    send_message_to_google_chat(@event)
  end

  private

  def set_event_and_member
    @event = Event.find params[:event_id]
    @members = @event.members.includes(:user)
  end

  def build_group_sizes(event)
    total_members = event.members.count
    max_group_size = event.max_group_size
    min_group_size = event.min_group_size
  
    group_sizes = []
    loop_count = -1

    while loop_count < 1000
      loop_count += 1
      remaining_members = total_members
      group_sizes = []

      # ループ毎に total_members を減少させる
      remaining_members = total_members - (max_group_size * loop_count) if loop_count > 0

      max_groups_count = loop_count > 0 ? (max_group_size * loop_count) / max_group_size : remaining_members / max_group_size
      
      max_groups_count.times { group_sizes << max_group_size }
      remaining_members = total_members - (max_group_size * max_groups_count)

      if remaining_members % min_group_size == 0
        # 割り切れる場合は最小グループを追加して終了
        min_groups_count = remaining_members / min_group_size
        min_groups_count.times { group_sizes << min_group_size }
        break
      end

    end
  
    group_sizes
  end

  def evenly_managers(members, group_sizes)
    # マネージャーと通常のメンバーを分ける
    manager_members = members.select { |member| member.user.position == 'manager' }
    normal_members = members.reject { |member| member.user.position == 'manager' }
    
    # 最大必要なマネージャーの数を group_sizes に基づいて決定
    required_managers = group_sizes.size
    
    # マネージャーをランダムに並び替え
    manager_members.shuffle!
    
    # 余ったマネージャーを通常メンバーに含める
    extra_managers = manager_members.drop(required_managers)
    
    # 必要な数だけマネージャーを抽出
    selected_managers = manager_members.take(required_managers)
    
    # 通常メンバーをランダムに並び替え、余ったマネージャーを含める
    normal_members.concat(extra_managers).shuffle!
    
    # 各グループにマネージャーを均等に分けて混ぜる
    mixed_members = []
    normal_members.each_slice(3).with_index do |slice, index|
      mixed_members.concat(slice)
      mixed_members << selected_managers[index] if index < selected_managers.size
    end
  
    mixed_members
  end  

  def group_members(members, group_sizes)
    grouped_members = {}
    current_index = 0
  
    # 各グループサイズに従ってメンバーを分割
    group_sizes.each_with_index do |group_size, index|
      group = members[current_index, group_size]
      grouped_members[index + 1] = group
      current_index += group_size
    end
  
    grouped_members
  end

  def create_groups(event, grouped_members)
    # アルファベットのリスト
    group_names = ('A'..'Z').to_a
    
    grouped_members.each_with_index do |(group_index, members), index|
      group_name = group_names[index]
      
      # sort_order をインデックス + 1 に設定
      group = Group.create!(
        event_id: event.id,
        group_name: "#{group_name}チーム",
        sort_order: index + 1
      )
      
      members.each do |member|
        member.update!(group_id: group.id)
      end
    end
  end

  def member_overlap?(grouped_members)
    latest_group = Group.order(created_at: :desc).first
    return true unless latest_group
  
    # 最新のグループに紐づくイベントを取得
    event = latest_group.event
  
    # イベントに紐づくグループを取得し、そのグループのメンバーを含める
    current_groups = event.groups.includes(:members)
  
    # grouped_members にある各グループごとに処理
    grouped_members.each do |group_index, members|
      next if members.nil? || members.empty?
      
      # 部署ごとのメンバー数をカウント
      department_counts = Hash.new(0)
      members.each do |member|
        department_id = member.user.department_id
        department_counts[department_id] += 1
  
        # 同じ部署のメンバーが3人以上いる場合はfalseを返す
        return false if department_counts[department_id] > 2
      end
  
      # 新しいメンバーのユーザーIDを取得
      new_member_ids = members.map(&:user_id)
  
      # 現在のグループと比較して同じメンバーがいるかを確認
      current_groups.each do |current_group|
        current_member_ids = current_group.members.pluck(:user_id)
  
        # 重複するメンバーIDを確認
        common_members = new_member_ids & current_member_ids
  
        # 1名以上同じメンバーがいれば false を返す
        return false if common_members.size >= 2
      end
    end
  
    true
  end

  def send_message_to_google_chat(event)
    webhook_url = ENV['GOOGLE_CHAT_WEBHOOK_URL']
  
    # グループとメンバー情報を整形
    group_details = event.groups.includes(:members).group_by(&:group_name).map do |group_name, groups|
      member_details = groups.map do |group|
        group.members.map { |member| "#{member.user.name}" }
      end.flatten
  
      "#{group_name}:\n" + member_details.join("\n")
    end.join("\n\n")
  
    # イベントの日付を指定のフォーマットで取得
    formatted_event_date = event.event_date.strftime('%Y年%m月%d日')
  
    # 送信するメッセージ
    message = {
      text: "[自動送信]\n" \
            "グループ分けが完了しました。\n\n" \
            "イベント詳細\n" \
            "=========================\n" \
            "開催日: \n" \
            "#{formatted_event_date}\n\n" \
            "イベント名: \n" \
            "#{event.title}\n\n" \
            "メモ: \n" \
            "#{event.memo}\n" \
            "=========================\n\n" \
            "[グループ分けの結果]\n\n#{group_details}"
    }
  
    # HTTPリクエストを送信
    uri = URI.parse(webhook_url)
    header = {'Content-Type': 'application/json'}
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    request = Net::HTTP::Post.new(uri.request_uri, header)
    request.body = message.to_json
  
    response = http.request(request)
    
    # レスポンスを確認
    if response.code == '200'
      puts 'メッセージがGoogle Chatに送信されました。'
    else
      puts "エラーが発生しました: #{response.body}"
    end
  end
end

app/controllers/admins/events/members_controller.rb
class Admins::Events::MembersController < Admins::BaseController
  skip_before_action :authenticate_admin!, only: [:show, :join]

  def show
    @event = Event.find params[:event_id]
    @member = @event.members.find(params[:id])
  end

  def join
    @event = Event.find_by(id: params[:event_id])
    @user = User.find_by(id: params[:user_id])
    return redirect_to admins_join_error_path unless @event && @user

    @member = Member.find_by(event: @event, user: @user)
    return redirect_to admins_event_member_path(@event, @member) if @member

    @member = Member.new(event: @event, user: @user)

    if @member.save
      redirect_to admins_event_member_path(@event, @member)
    else
      redirect_to admins_join_error_path
    end
  end

  def join_error; end

  def resend
    @event = Event.find params[:event_id]
    @user = User.find params[:id]
    EventMailer.participation(@user, @event).deliver_later

    redirect_to admins_event_path(@event), notice: 'イベント案内を再送しました。'
  end
end

app/controllers/admins/events_controller.rb
class Admins::EventsController < Admins::BaseController
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.invitees_count = User.enabled.count
  
    if @event.save
      users = if params[:event][:include_executives] == "true"
                User.enabled
              else
                User.enabled.where.not(position: :executive)
              end
  
      users.find_each do |user|
        EventMailer.participation(user, @event).deliver_later
      end
  
      redirect_to admins_event_path(@event), notice: 'イベント作成に成功しました。'
    else
      flash[:alert] = "作成に失敗しました。"
      render :new, status: :unprocessable_entity
    end
  end
  

  def show
    @event = Event.includes(members: { user: :department }).find(params[:id])
    @join_users = @event.users.includes(:department).ordered_position
    @non_members = User.enabled.ordered_position.where.not(id: @event.members.select(:user_id))
    member_user_ids = @event.members.pluck(:user_id)
    @non_members = User.enabled.includes(:department).ordered_position.where.not(id: member_user_ids)
  end

  def destroy
    @event = Event.find params[:id]

    return redirect_to admins_root_path, alert: '削除するイベントが見つかりませんでした。' if @event.nil?

    if @event.destroy
      redirect_to admins_root_path, notice: 'イベント削除に成功しました。'
    else
      redirect_to admins_event_path(@event), alert: 'イベント削除に失敗しました。'
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :memo, :max_group_size, :min_group_size, :state, :event_date)
  end
end

app/helpers/admins/events_helper.rb
module Admins::EventsHelper
end

app/views/admins/events/new.html.slim
.container
  .header-container
    h2.heading-ttl イベント作成画面

  .template
    .template__container
      p.template__ttl テンプレートから選択
      a href="#" class="template__link" data-template="1" シャッフルランチ

  .form-container
    = form_with(model: [:admins, @event], local: true) do |f|
      .form-inner
        .form-item
          = f.label :title, 'イベント名', class: 'required-label label-font'
          = f.text_field :title, class: 'form-control title-field', placeholder: '例：シャッフルランチ (最大15文字)'

        .form-item
          = f.label :event_date, 'イベント日時', class: 'required-label label-font'
          = f.date_field :event_date, class: 'form-control date-field', min: Date.today

        .form-item
          = f.label :group_size, '１グループの人数', class: 'required-label label-font'
          .group-size-fields
            = f.number_field :min_group_size, class: 'form-control group-size min-size-field', min: 1, placeholder: '3'
            span.separator 〜
            = f.number_field :max_group_size, class: 'form-control group-size max-size-field', min: 1, placeholder: '4'
            span.unit 人
          .explanation-txt
            | ※有効ユーザー数: #{User.enabled.count}人
            br
            | ※最小人数と最大人数の差は1人以内に設定してください。
            br
            |（例: 3〜2人や4〜3人など）

        .form-item
          = label_tag :include_executives, '条件設定', class: 'label-font'
          .flex-container
            .custom-checkbox
              = check_box_tag 'event[include_executives]', true, false, id: 'include_executives'
            = label_tag :include_executives, '役員有り', class: 'label-font'
          .explanation-txt
            | ※デフォルトで「前回メンバーとの重複」と「同部署2名以上の配置」を防止する設定がされています。

        .form-item
          = f.label :memo, 'メモ', class: 'label-font'
          = f.text_area :memo, class: 'form-control memo-field', placeholder: '例: 今日のお題: 会社の中で一番尊敬できる人（最大150文字）'

        = f.submit 'イベントの作成', class: 'btn-submit confirm-btn'

        .notification
          p ※作成と同時にメンバーへ出欠確認メールを送信します。

app/views/admins/events/show.html.slim
.container
  .header-container
    h2.heading-ttl イベント詳細

  .event-details

    - unless @event.groups.exists?
      .event-details__shuffle-botton
        = button_to 'グループ分け', admins_event_groups_path(@event), method: :post, class: 'event-details__btn-submit confirm-btn'

    h3.event-details__title
      = @event.title

    .event-info
      p.event-details__date
        span.label 日付: 
        = @event.event_date.strftime('%Y年%m月%d日')
        
      p.event-details__group-size
        span.label グループ人数: 
        span= "#{@event.min_group_size}~#{@event.max_group_size}人"

      p.event-details__memo-title
        span.label メモ:
        = simple_format(@event.memo)

    - if @event.groups.present?
      h3.event-details__title
        | グループ
      .group-container
        - @event.groups.group_by(&:group_name).each do |group_name, groups|
          .group__card
            .group__header
              p = group_name
            .group__body
              ul.group__member-list
                - groups.each do |group|
                  - group.members.each do |member|
                    li.group__member-item
                      span.group__member-name = "#{member.user.name}"

    - else
      h3.event-details__title
        | メンバー
      .area
        input#tab1(type="radio" name="tab_name" checked)
        label.tab_class(for="tab1") 参加メンバー

        input#tab2(type="radio" name="tab_name")
        label.tab_class(for="tab2") 未参加ユーザー

        #content1.content-box
          table.table.pc-table
            thead
              tr
                th 部署
                th 氏名
                th メールアドレス
                th 役職
            tbody
              - @join_users.each do |user|
                tr
                  td = user.department.name
                  td
                    = link_to user.name, admins_user_path(user), class: 'table__name'
                  td = user.email
                  td = position_badge(user)

        #content2.content-box
          table.table.pc-table
            thead
              tr
                th 部署
                th 氏名
                th メールアドレス
                th 役職
                th 再送
            tbody
              - @non_members.each do |user|
                tr
                  td = user.department.name
                  td
                    = link_to user.name, admins_user_path(user), class: 'table__name'
                  td = user.email
                  td = position_badge(user)
                  td
                    = button_to resend_admins_event_member_path(@event, user), method: :post, class: 'resend-button' do
                      = image_tag 'email.png', alt: 'メール再送信', class: 'email-icon'


        // SP画面用のリスト表示
        #content1.content-box
          ul.list-view
            - @join_users.each do |user|
              li
                = link_to admins_user_path(user), class: 'list-view__link' do
                  .list-view__icon
                    = image_tag 'account_circle.png', alt: 'user', class: 'icon-user'
                  .list-view__user-name = user.name
                  .list-view__arrow
                    = image_tag 'arrow_icon.png', alt: 'arrow', class: 'icon-arrow'

        #content2.content-box
          ul.list-view
            - @non_members.each do |user|
              li
                = link_to admins_user_path(user), class: 'list-view__link' do
                  .list-view__icon
                    = image_tag 'account_circle.png', alt: 'user', class: 'icon-user'
                  .list-view__user-name = user.name
                  .list-view__arrow
                    = image_tag 'arrow_icon.png', alt: 'arrow', class: 'icon-arrow'

    .event-details__delete-btn
      = link_to 'イベントを削除', admins_event_path(@event), data: { turbo_method: :delete }, class: 'event-details__btn', onclick: "return confirm('本当にこのイベントを削除しますか？')"